### ISSUE TITLE
unexpected keyword argument 'device_id'

### ISSUE THREAD

**Issue by stollem** [svasek/homeassistant-vistapool-modbus#199]
### Pre-flight checklist

- [x] I am using the latest released version of this integration.
- [x] The issue is in this integration, not in the underlying library.
- [x] I searched existing issues and this is not a duplicate.

### Integration version

6.0.0

### Home Assistant version

2025.7.2

### Device / brand

Hayward

### What happened?

The integration started failing completely right after upgrading to v6.0.0

The error is:

Einrichtungsfehler, wird erneut versucht: An error occurred while communicating with the NeoPool controller: Read error at 0x0100: ModbusClientMixin.read_input_registers() got an unexpected keyword argument 'device_id'

### Expected behaviour

The integration can read from the pool controller

### Steps to reproduce

Upgrade to v6.0.0

Click on "settings"-> "integrations" -> "NeoPool Modbus"

### Relevant logs

```text
Couldn't find where to download these
```

**Comment by svasek** [comment]
Hi @stollem,

This is a perfect storm of three things colliding, not something I could fully prevent on my side:

1. **pymodbus changed its API** in version 3.10 — they renamed the `slave=` keyword to `device_id=`. The `neopool-modbus` library was updated to use the new name.
2. **Home Assistant pins a specific pymodbus version** through its built-in `modbus` integration, and since HA 2025.8 also locks it via `package_constraints.txt`. Custom integrations can't override that pin, so the version of pymodbus your HA has installed is whatever HA itself decided to ship.
3. **You're running HA 2025.7.2**, which still ships **pymodbus 3.9.2** (`slave=`). HA 2025.8.0 was the first release to bump pymodbus to 3.11.x (`device_id=`), which is what the integration v4.x and newer needs.

That said, I should have raised the minimum HA version in `hacs.json` when releasing v4.0.0 to keep HACS from offering it to you in the first place. I'll push a patch for that shortly.

**Your options:**

1. **Upgrade Home Assistant to at least 2025.8.0** (recommended) — ships pymodbus 3.11.x and v6.x will just work.
2. **Downgrade the integration to v3.0.0** in HACS and ignore future updates — that's the last release that still ships its own pymodbus compatibility shim (`modbus_compat`) and works against pymodbus 3.9.x.

Sorry for the inconvenience!
